### ISSUE TITLE
Design Template for main screen

### ISSUE THREAD

**Issue by deepanshu-rawat6** [upes-open/OSoC-bio.lnk#1]
Figma Link to be added soon🫡

**Comment by divyansh2375** [comment]
should we have to make this template using html css?

**Comment by deepanshu-rawat6** [comment]
@divyansh2375 since it's a basic template design, so you can create a template on figma

**Comment by ArshdeepKaur04** [comment]
Hey, I would like to contribute on this issue. How can I move forward?

**Comment by deepanshu-rawat6** [comment]
@ArshdeepKaur04 Please find the figma files link in the bio-lnk channel in our discord server. 

Also, for moving forward with this issue, I'll create basic design template soon, and then you can add-on features accordingly

**Comment by shradiphylleia** [comment]
would like to work.

**Comment by ArshdeepKaur04** [comment]
Sure sir.
Waiting for the Template!

Regards,
Arshdeep Kaur

**Comment by deepanshu-rawat6** [comment]
Hey @ArshdeepKaur04 , I'd request you work on the user page( Issue #2 ), I can tell you about the idea of what elements we can keep, and all features we can include, so if you're interested you can drop a text on bio-lnk channel in our discord.

**Comment by ArshdeepKaur04** [comment]
Alright sir. Will connect tomorrow.

Thanks & Regards,
Arshdeep Kaur

**Comment by deepanshu-rawat6** [comment]
Sure @ArshdeepKaur04 , let's have a VC regarding #2  at 9PM today
