### ISSUE TITLE
User Authentication: Implement simple login and signup🔒

### ISSUE THREAD

**Issue by deepanshu-rawat6** [upes-open/OSoC-bio.lnk#21]
For basic user schema

- Username
- Hashed password

Make sure to store the user password hashed by either brycpt or any under hash generator.

**Comment by vasanthanb** [comment]
I can work on this issue

**Comment by vasanthanb** [comment]
> Hi ! i am already workingg on the login using google oauth

Ok no problem 👍, I thought it's not assigned

**Comment by ap766** [comment]
No I think this issue is for normal  signup and signing , so you can work on that

**Comment by vasanthanb** [comment]
Ok thank you 👍

**Comment by vasanthanb** [comment]
@deepanshu-rawat6 can you assign me this issue under osoc'23

**Comment by deepanshu-rawat6** [comment]
Sure @vasanthanb, I'll assign you this issue✨

**Comment by rohin079** [comment]
I would like to work on this issue under OSoC'23
