### ISSUE TITLE
DB Design: Create DB schemas for keeping integration platform data

### ISSUE THREAD

**Issue by deepanshu-rawat6** [upes-open/OSoC-bio.lnk#23]
Note: Keeping separate collections for all integrated platforms. To refer to a particular entry in these collection, make sure to use ``user_id``,  to map user data with data obtained from integrated platforms

**Comment by deepanshu-rawat6** [comment]
For reference, follow up with this diagram, [here](https://www.canva.com/design/DAFpEyMnh_Y/LDuNkbwHxOeIBLuQEXfuyA/edit?utm_content=DAFpEyMnh_Y&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton), and find information under **Integration Platforms**,

**Comment by rohin079** [comment]
I would like to work on this issue under OSoC'23

**Comment by deepanshu-rawat6** [comment]
Sure @rohin079 , I'll assign you this issue✨
