### ISSUE TITLE
User authentication using Google OAuth

### ISSUE THREAD

**Issue by deepanshu-rawat6** [upes-open/OSoC-bio.lnk#3]

**Comment by ap766** [comment]
Could I work on this ?

**Comment by deepanshu-rawat6** [comment]
Yes sure @ap766, I'll assign you this issue.

**Comment by rohin079** [comment]
@deepanshu-rawat6 hey, do want passport.js to be used in this?

**Comment by deepanshu-rawat6** [comment]
Yes @rohin079 , we need to have any out of Passport.js, Auth0 or Okta. But I think, Passport.js would be the best for our project 

Also let's say we have a profile of **XYZ** user
And later on, we check if the user is **XYZ** then he can edit his/her profile. Otherwise, he/she can only view the profile of XYZ, and separate options will be there for him/her(non-authenticated).

**Comment by rohin079** [comment]
I would like to work on this issue under OSoC'23
