### ISSUE TITLE
User schema for basic details

### ISSUE THREAD

**Issue by deepanshu-rawat6** [upes-open/OSoC-bio.lnk#7]

**Comment by Basavachari** [comment]
Hello Deepanshu,
I would like to resolve this issue.
May I have some detailed information for this issue

**Comment by deepanshu-rawat6** [comment]
Sure @Basavachari, I'll assign you this issue.

Currently, you'll need create a basic schema using ```mongoose```, which has following fields:

*  Username
*  Email
*  Hashed password

But, surely we would update these  as the other issues get completed
