### ISSUE TITLE
Create navbar for main page

### ISSUE THREAD

**Issue by deepanshu-rawat6** [upes-open/OSoC-bio.lnk#9]

**Comment by ChrisJon02** [comment]
I want to work on this issue. But are the requirements of the navbar?

**Comment by GaganChaudhary6378** [comment]
Hi, I want to work for this issue will you please assign it to me.

**Comment by deepanshu-rawat6** [comment]
Hi @GaganChaudhary6378, I'd recommend first creating a design template in figma, then we can proceed with this issue. For more details, checkout **bio.lnk** channel on our discord server

**Comment by Siddharthaaa21** [comment]
Hey ! would like to work on it. Could you tell me your requirements or what you have in your mind ?

**Comment by deepanshu-rawat6** [comment]
Sure @Siddharthaaa21 I'll assign you this issue, but first we'll create a basic design template and then we can proceed with this issue.

**Comment by anmol-gh** [comment]
hey, now that the design is ready, I'd like to work on this. can you please assign this?

**Comment by deepanshu-rawat6** [comment]
Sure, @anmol-gh 
Issue Assigned!
